use_frameworks!

platform :ios, '9.0'

target 'HXLeetCode_Example' do
  pod 'HXLeetCode', :path => '../'
  pod 'AFNetworking'
  
  
  target 'HXLeetCode_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
  end
end
